CSeqIdException: Add an export specifier, since the class isn't fully inline anymore.  JIRA: CXX-7524.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@69634 112efe8e-fc92-43c6-89b6-d25c299ce97b